### ISSUE TITLE
Feature: User can register for the app using their Google account.

### ISSUE THREAD

**Issue by sryuocampo** [sryuocampo/bark-at-the-park#1]
## ⚙️ Feature

Users can log into the app with their Google email account. 

## 📐 Functionality

When they open the app it will open to the sign in page where they can click the "Sign in with Google" button to be logged in via their Google account. 

## 🖼️ Wireframes
![sign in paw](https://user-images.githubusercontent.com/78890855/120049543-2718bc00-bfcf-11eb-99c1-35ca58e86c0c.PNG)
![google sign in web paw](https://user-images.githubusercontent.com/78890855/120049546-2849e900-bfcf-11eb-99d9-00b94b1b8647.PNG)

### 🐘 Database

- [x] Go to Firebase and create an account
- [x] Go to the Authentication tab under Build and click on "Create database"
- [x] Follow the prompt provided, starting in production mode
- [x] Next go to the Firestore tab under Build and follow the prompts to get the Cloud Firestore database set up. 

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Create index.html and set up a basic html body
- [x] Create a heading element for "Bark at the Park"
- [x] Create a paragraph element for "A place for your furry friend to make their own furry friend."
- [x] Create index.jsx
- [x] Add the npm dependencies for react, react-dom, and Firebase SDK
- [x] to install firebase npm package make sure you have a package.json created, if not run the command "npm init"
- [x] To install firebase npm pakcage and save it to package.json run the command "npm install --save firebase"
- [x] Use import to include only the specific Firebase products Authentication and Cloud Firestore. 
- [x] Use CSS to style the sign in page by adding Amatic SC to the heading and Spectral to the paragraph text
- [x] Create a div with the className "sign-in-button" 
- [x] Inside the div create an input with a type value of image and a src to the icon of your choice
- [x] Below that copy in  ```
<button
            className="google-sign-in"
            onClick={() => {
              const googleAuthProvider = new firebase.auth.GoogleAuthProvider();
              firebase.auth().signInWithPopup(googleAuthProvider);
            }}
          >
            Sign in with Google
          </button>

```

- [ ] Use CSS to style 
### ☁️ Server

- Firebase is a serverless solution with a NOSQL and built in API. 

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
