### ISSUE TITLE
Feature: Users can submit their profile information to save to the Firestore database. 

### ISSUE THREAD

**Issue by sryuocampo** [sryuocampo/bark-at-the-park#2]
## ⚙️ Feature

User can view the google maps, see the "Go to the Park!" button and their icon button. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view the main page where the google map is with two buttons. If they click on the icon in the upper right corner it pops up the "Bark Profile" where they can see the pop up of where their information can be written, such as name and size of their animal along with where their icon would go. 
## 🖼️ Wireframes

![bark profile mobile](https://user-images.githubusercontent.com/78890855/119610754-906db480-bdae-11eb-823f-cce5d4e9af2d.PNG)
![bark profile web](https://user-images.githubusercontent.com/78890855/119610760-919ee180-bdae-11eb-9c02-8e94f21af03f.PNG)

## ✅ Task List

- [x] Create info.jsx and info.css
- [x] In info.jsx import react and info.css
- [x] Created Info component that shows the users "Bark Profile" 
- [x] Within the component created a div where the image icon for the users dog will go, including a static google icon which will allow users to choose a dog icon in the next feature. 
- [x] Create an input type=text and an select element 
- [x] Adding an onClick attribute with the value {props.onClose} to the <button> elements with the className "submit" and "cancel"
- [x] Within info.css style the "Bark Profile" to mirror the example above. 
- [x] Create a map.jsx and map.css
- [x] install react-google-maps/api by typing into the consolue "npm i -S @react-google-maps/api"
- [x] In map.jsx import {GoogleMap, LoadScript} 
- [x] import React, Info, and map.css
- [x] Following npm react google maps api documentation insert the const variables containerStyle and center
- [x] Create a Map component and create a `const [showProfile, setShowProfile] = React.useState(false); `within return  
```
<LoadScript googleMapsApiKey="YOUR_API_KEY">
        <GoogleMap
          mapContainerStyle={containerStyle}
          center={center}
          zoom={13}
          options={{
            fullscreenControl: false,
            streetViewControl: false,
            mapTypeControl: false,
            zoomControl: false
          }}
>
</GoogleMap>
</LoadScript>
```
- [x] Get your API key by signing up for Google Maps Platform then inserting that specific key into the code
- [ ]Create a button element with the attributes id= "profile",  style="", and onClick for setShowProfile(true)
- [x] create a ternary operator with the condition showProfile and if truthy <Info onClose={( ) => setShowProfile(false)}/> if falsy null. 
- [x] Import {FirestoreMutation} from @react-firebase/firestore
- [x] Create a function component Info with 3 properties {initProfile, onSave, onClose}
- [x] In the Info component body create a const variable deconstructing from the React useState hook [profile, setProfile] and inside the hook it'll get the initProfile or show the profile for a new user which is a blank name and size and the first icon 001.png
- [x] Outside the Info compononet we will export the function InfoWithFirestoreMutation with the parameters ({auth, initProfile, onClose}) 
- [x] In the function body we will return the FirestoreMutation with the path /user_pets/${auth.user.uid}
- [x] When the mutation is run if it's onClose it'll just close however if it is summited it will save to the backend then close. 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
