### ISSUE TITLE
Feature: Users can allow geolocation to access their location and set the map to their coordinates. 

### ISSUE THREAD

**Issue by sryuocampo** [sryuocampo/bark-at-the-park#7]
## ⚙️ Feature

The users will be able to see their location on the map. 

## 📐 Functionality

If the user allows us access to their location the map will render to where they are. 

## 🖼️ Wireframes

![mobile location](https://user-images.githubusercontent.com/78890855/120594041-2fb92a00-c3f5-11eb-8dc6-8e1395c8c4bd.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] In map.jsx add mapCenter state using the useState hook
- [x] Add a useEffect hook on mount to request access to geolocation 
- [x] If the geolocation is allowed update the mapCenter state to the users geolocation 
- [x] Upload an icon of your choice to the Icons folder 
- [x] Above the goingtoPark button import the img with the className to style it in css

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
